name: CI Pipeline - Intranet NewDeal

on:
  push:
    branches:
      - dev 

env:
  IMAGE_NAME: intranet-newdeal
  IMAGE_TAG: latest
  DOCKER_REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true   # ✅ FIX Node.js

jobs:

  # ===============================
  # JOB 1 - BUILD + PUSH
  # ===============================
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v5   # ✅ FIX Node 24

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG .

      - name: Push Docker image   # ✅ IMPORTANT
        run: |
          docker push $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

  # ===============================
  # JOB 2 - SECURITY SCAN
  # ===============================
  scan:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Pull image manually   # ✅ IMPORTANT
        run: |
          docker pull $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@v0.20.0
        with:
          image-ref: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: table
          severity: CRITICAL,HIGH
          vuln-type: os,library
          ignore-unfixed: true
          exit-code: 0